### ISSUE TITLE
My 3490 won't boot after the first install process

### ISSUE THREAD

**Issue by jeffreyvh** [huburtx/Dell-Latitude-3490-hackintosh-Open-Core#1]
Hi,

I've tried to install Big Sur on my Latitude 3490. I am having these specs :

i5-8250u
Samsung Evo 850 256GB (2,5" sata drive)
Hyonix M2 (Came OOB, Windows is installed on it)
16GB DDR4 (OOB)

What I did : 

Made the USB bootable using a Mac (Appstore method)
Mounted the EFI partition
Copied your EFI folder onto the USB EFI folder
Removed the Brcmfixup and etc (From Kext folder and from config)
Booted from USB

This is my problem,

When I boot from the USB, it's showing me the selection menu. I chose install (External). I succesfully booted in the installer. I used disk utility to format the Samsung SSD (APFS, GUID). Then started the install. After the first reboot I tried to boot from the USB again. This resolved into a black screen. I just can't continue to the device (boot) selection menu from OpenCore.

Any help would be appreciated.

**Comment by huburtx** [comment]
Hello,

1. Did you add your SMBIOS values in config.plist>PlatformInfo>General (Serial No, MLB, etc.)?
2. Did you set properly bios options?
3. The Big Sur installation process is very slow, set in bios boot option your USB drive as first option. Launch the installer and go to watch a film in TV. The process need 3~4 reboots to complete.

**Comment by jeffreyvh** [comment]
Hi,
1. Yes I did
2. Yes I did
3. The problem is that I am not able to get to the boot menu (OpenCore), it would just really short give me the message :

OCS: No schema for 3 at 12 index, context <Patch> |

And after this (The message is only visible like half a second) the screen turns black and sometimes the laptop then just reboots (Not always).

**Comment by huburtx** [comment]
That message is normal. **You have to be patience and wait**.  Follow these steps:

1. Make usb bootable like in [Dortania guide](url)https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#downloading-macos-modern-os or download from Apple store and write on USB.

2. Copy EFI folder without all Broadcom kexts to EFI partition

3. Set Bios and Config as indicated

4. Set your USB drive as first boot option in BIOS

5. Plug in the AC adapter and launch Mac Os Installer (External)

6. Choose your destination SSD and erase it (Utility disk > show all devices > APFS/GUID > Erase)

7. Launch the installation and **wait a long time** black screens is normal during installation and reboots also.

8. Do not interrupt the installation process

**Comment by huburtx** [comment]
That message is normal. **You have to be patience and wait**.  Follow these steps:

1. Make usb bootable like in [Dortania guide](https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#downloading-macos-modern-os) or download from Apple store and write on USB.

2. Copy EFI folder without all Broadcom kexts to EFI partition

3. Set Bios and Config as indicated

4. Set your USB drive as first boot option in BIOS

5. Plug in the AC adapter and launch Mac Os Installer (External)

6. Choose your destination SSD and erase it (Utility disk > show all devices > APFS/GUID > Erase)

7. Launch the installation and **wait a long time**. Black screens is normal during installation and reboots also.

8. Do not interrupt the installation process

**Comment by jeffreyvh** [comment]
The Issue is that I am not able to get to the boot picker (OpenCore), my laptop then just hangs on a black screen, so I am not able to boot either from my installation USB nor the SSD with a partial install of Mac OS Big Sur.

https://www.reddit.com/r/hackintosh/comments/gn41rk/stuck_in_oc_watchdog_status_is_0/frfx5wu/?context=3 (Someone with a similar issue, not the same but quite similar)

**Comment by huburtx** [comment]
1. Post here your edited EFI
2. Bios version?
3. Post here all bios settings (photo in a zipped folder)

For first we need to check these things.
